site_name: "Botshare Book"
site_url: "https://botshareai.github.io/Botshare_book/"
repo_url: "https://github.com/openAMRobot"

theme:
  name: "material"
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight

extra:
  copyright_html: "© 2025 <a href='https://botshare.ai'>Botshare AI</a>. All rights reserved."
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:info@botshare.ai
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/botshare
  copyright: "© 2025 Botshare AI. All rights reserved."

  use_directory_urls: false
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - L1_Incubation: L1_Incubation.md
  - L2_Acceleration: L2_Acceleration.md
  - Use cases: use_cases.md
  - Contributing: contributing.md
  - Company overview: company_overview.md
  - FAQ: faq.md
  - References: references.md

plugins:
  - search:
      lang: en
